/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommendations
         * @description Ranked hall/meal picks. With no date or meal, plans the rest of today from now on;
         *     missing goal fields fall back to the user's saved settings.
         */
        post: operations["recommendations_api_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meals
         * @description Meal names served on `date` (default today) across all halls, in serving order.
         */
        get: operations["meals_api_v1_meals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Fields */
            fields?: {
                [key: string]: string;
            } | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** Goal */
        Goal: {
            /** Protein G */
            protein_g: number;
            /** Calories */
            calories: number;
        };
        /** MealsResponse */
        MealsResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Meals */
            meals: string[];
        };
        /** MetaResponse */
        MetaResponse: {
            /**
             * Calendar Source
             * @enum {string}
             */
            calendar_source: "ical" | "google" | "none";
        };
        /** Nutrition */
        Nutrition: {
            /** Calories */
            calories: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Serving Size */
            serving_size: string;
        };
        /** PlateItem */
        PlateItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Station */
            station: string;
            /** Is Vegetarian */
            is_vegetarian: boolean;
            /** Allergens */
            allergens: string[];
            nutrition: components["schemas"]["Nutrition"] | null;
        };
        /** RecommendationOut */
        RecommendationOut: {
            /** Rank */
            rank: number;
            /** Dining Hall */
            dining_hall: string;
            /** Meal */
            meal: string;
            window: components["schemas"]["Window"];
            scores: components["schemas"]["Scores"];
            /** Plate */
            plate: components["schemas"]["PlateItem"][];
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /** Date */
            date?: string | null;
            /** Meal */
            meal?: string | null;
            /** Protein */
            protein?: number | null;
            /** Calories */
            calories?: number | null;
            /** Meals */
            meals?: number | null;
        };
        /** RecommendationsResponse */
        RecommendationsResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Meal */
            meal: string | null;
            goal_per_meal: components["schemas"]["Goal"];
            /** Windows */
            windows: components["schemas"]["Window"][];
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationOut"][];
            /** Notice */
            notice?: string | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** Scores */
        Scores: {
            /** Total */
            total: number;
            /** Nutrition */
            nutrition: number;
            /** Time */
            time: number;
            /**
             * Proximity
             * @description null when your location around the window is unknown
             */
            proximity: number | null;
        };
        /** Settings */
        Settings: {
            /** Protein Target G */
            protein_target_g: number;
            /** Calorie Limit */
            calorie_limit: number;
            /** Meals Per Day */
            meals_per_day: number;
            /**
             * Day Start
             * @description 24-hour HH:MM
             */
            day_start: string;
            /**
             * Day End
             * @description 24-hour HH:MM
             */
            day_end: string;
            /** Restricted Keywords */
            restricted_keywords: string[];
            /** Building Coords */
            building_coords: {
                [key: string]: [
                    number,
                    number
                ];
            };
        };
        /** Window */
        Window: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Prev Event Location */
            prev_event_location?: string | null;
            /** Next Event Location */
            next_event_location?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recommendations_api_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    meals_api_v1_meals_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealsResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
